### ISSUE TITLE
Version 1.0.9 specifies version 1.0.8 in it's bower.json file.

### ISSUE THREAD

**Issue by mmontagna** [angular-ui/angular-ui-router-bower#2]
The title is pretty self explanatory the version appears not to have been bumped. I think this is causing my bower install to fail with: 

```
bower angular-ui-router#^1.0.8         mismatch Version declared in the json (1.0.8) is different than the resolved one (1.0.9)
```

**Comment by erickwilder** [comment]
This is also happening with the latest `1.0.10` version. Something is broken with the publishing code. This repo is updated by a script[1] of the main `ui-router` repo.

[1] https://github.com/angular-ui/ui-router/blob/master/scripts/bower_release.js#L15

**Comment by christopherthielen** [comment]
FWIW the bower publish script was fixed in https://github.com/angular-ui/ui-router/commit/ab50f1bfde44c8193f46cfe52f7e0720aa442ac5
