### ISSUE TITLE
Latest release 1.0.20 is a few versions behind angular ui-router

### ISSUE THREAD

**Issue by davidclark87** [angular-ui/angular-ui-router-bower#3]
Hi @christopherthielen, would it be possible to add a release for ui-router 1.0.22? Or is this repo no longer maintained?

**Comment by christopherthielen** [comment]
it's maintained.  the bower releases are published automatically, so I'll have to see what has broken.

**Comment by christopherthielen** [comment]
I'm not sure what automation has broken, but I've released versions 1.0.21 and 1.0.22 on bower.

**Comment by davidclark87** [comment]
Thanks @christopherthielen !
